#!/bin/bash
#!/bin/bash
# Author: @shadowelite
# Date: 22-07-2022
# Description: crypto decoder
# https://github.com/shadowelite-sec

banner(){
	echo -e "\n ██████╗██████╗ ██╗   ██╗██████╗ ████████╗
██╔════╝██╔══██╗╚██╗ ██╔╝██╔══██╗╚══██╔══╝
██║     ██████╔╝ ╚████╔╝ ██████╔╝   ██║   
██║     ██╔══██╗  ╚██╔╝  ██╔═══╝    ██║   
╚██████╗██║  ██║   ██║   ██║        ██║   
 ╚═════╝╚═╝  ╚═╝   ╚═╝   ╚═╝        ╚═╝   
                                          "

	echo -e -n "1) Base64   2) Brainfuck\n3) Stego    4) Base32\n\n"
}
b64(){
	echo -e "\n1) for decode base64\n2) for encode base64\n\n"
	read -e -p 'Select Any : ' en 
	if [[ "$en" == 1  ]];then
		echo -n "Enter the String : "
		read str
		echo -e "\n"
		echo "$str" | base64 -d

	elif [[ "$en" == 2 ]];then
		echo -n "Enter the String : "    
                read str
		echo -e "\n"
                echo "$str" | base64 
	else
		main
	fi
}

b32(){
	echo -e "\n1) for decode base32\n2) for encode base32\n\n"    
        read -e -p 'Select Any : ' en     
        if [[ "$en" == 1  ]];then    
                echo -n "Enter the String : "    
                read str
		echo -e "\n"
                echo "$str" | base32 -d    
    
        elif [[ "$en" == 2 ]];then    
                echo -n "Enter the String : "        
                read str
		echo -e "\n"
                echo "$str" | base32                                                  
        else                                                                          
                main                                                                  
        fi
}

steg(){
	echo -e "\n1) For Extract Data Frome Img(.jpg)\n2) For Embed Data To Img(.jpg)n\n"    
        read -e -p 'Select Any : ' en
        if [[ "$en" == 1  ]];then
                echo -n "Enter Path To File : "    
                read -e img
                steghide extract -sf $img

        elif [[ "$en" == 2 ]];then
                echo -n "Enter Path To Img : "        
                read img
		echo -n "Enter Path To Data : "
		read data
		steghide embed -cf $img -ef $data
		
                
        else
                main
        fi
}

brainfuck(){
	   read -e -p 'Enter The Brainfuck Code To Decode : ' en
	   echo -e "\n"
	   echo "$en" | brainbash
}

main(){
	banner
	read -e -p 'Select Option : ' value

	case $value in

	  1)
	    b64
	    ;;

	  2)
	    brainfuck
	    ;;

	  3)
	    steg
	    ;;

	  4)
	    b32
	    ;;

	   *)
	echo "Invalid Input exiting ....!"
	exit 1
esac
}

#``read -e -p 'Select Option :' 1
if [[ -z $1 ]];then
	main
else
	echo "args experimental"

fi
